### ISSUE TITLE
error: MongoError: server ${mongoHost}:27017 sockets closed

### ISSUE THREAD

**Issue by jamesongithub** [kissjs/node-mongoskin#191]
seeing a lot of sockets closed errors after upgrading to node driver version 2.0.55 and mongoskin 2.0.3 on mongodb v3.0.10

```
17:18:38 2016-04-07T17:18:42.656Z - error: MongoError: server ${mongoHost}:27017 sockets closed
17:18:38     at null.<anonymous> (${PATH}/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:330:47)
17:18:38     at g (events.js:260:16)
17:18:38     at emitTwo (events.js:87:13)
17:18:38     at emit (events.js:172:7)
17:18:38     at null.<anonymous> (${PATH}/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:105:12)
17:18:38     at g (events.js:260:16)
17:18:38     at emitTwo (events.js:87:13)
17:18:38     at emit (events.js:172:7)
17:18:38     at Socket.<anonymous> (${PATH}node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:145:12)
17:18:38     at Socket.g (events.js:260:16)
17:18:38     at emitOne (events.js:77:13)
17:18:38     at Socket.emit (events.js:169:7)
17:18:38     at TCP._onclose (net.js:475:12) server ${mongoHost}:27017 sockets closed
17:18:38 
```

**Comment by hustcer** [comment]
I got the same error, too. Any one can help?

**Comment by hustcer** [comment]
@vkarpov15 Any ideas? Thanks

**Comment by hustcer** [comment]
BTW, I got this error when my server upgrade to Ubuntu 16.04 with node version `v6.1.0`, and for 14.04 it works well.
